# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "PaymentKit Example" do
 pod "TOMSMorphingLabel"
 pod "JVFloatLabeledTextField", :path => "../../JVFloatLabeledTextField"
end

target "PaymentKit Test" do

end

